"""
Trade Proposal — immutable value object representing a pending entry recommendation.

A proposal is generated by the research engine, presented to the human, and
either approved (within its expiry window) or discarded.  Only approved
proposals may be passed to order_executor.place_bracket_order().
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional, Tuple

from trading_agent import config
from trading_agent.research_engine import MacroSnapshot, RankedCandidate


@dataclass(frozen=True)
class TradeProposal:
    symbol: str
    entry_price_low: float
    entry_price_high: float
    stop_price: float
    target_price: float
    position_size_dollars: float
    reasoning: str
    expiration: datetime           # timezone-aware UTC
    macro_context: str
    stop_pct: float
    target_pct: float
    reward_risk_ratio: float
    is_leveraged_etf: bool = False
    wash_sale_flag: bool = False
    wash_sale_days_remaining: int = 0

    @property
    def entry_midpoint(self) -> float:
        return (self.entry_price_low + self.entry_price_high) / 2

    def is_expired(self, now: Optional[datetime] = None) -> bool:
        if now is None:
            now = datetime.now(tz=timezone.utc)
        if now.tzinfo is None:
            now = now.replace(tzinfo=timezone.utc)
        return now >= self.expiration

    def is_price_in_range(self, current_price: float) -> bool:
        """Check whether current_price is still within the approved entry range."""
        return self.entry_price_low <= current_price <= self.entry_price_high


def create_proposal(
    candidate: RankedCandidate,
    position_size_dollars: float,
    entry_spread_pct: float = 0.005,  # ±0.5% around current price for limit range
    created_at: Optional[datetime] = None,
) -> TradeProposal:
    """
    Build a TradeProposal from a RankedCandidate + approved dollar amount.

    `entry_spread_pct` sets how wide the limit-order entry range is around the
    current price.  Defaults to ±0.5% to allow slight slippage while keeping
    the entry disciplined.
    """
    if created_at is None:
        created_at = datetime.now(tz=timezone.utc)
    elif created_at.tzinfo is None:
        created_at = created_at.replace(tzinfo=timezone.utc)

    from datetime import timedelta
    expiration = created_at + timedelta(hours=config.ENTRY_RECOMMENDATION_EXPIRY_HOURS)

    price = candidate.technical.current_price
    entry_low = round(price * (1 - entry_spread_pct), 4)
    entry_high = round(price * (1 + entry_spread_pct), 4)

    rr = candidate.risk_reward
    macro = candidate.macro

    reasoning_parts = [
        f"Symbol: {candidate.symbol}",
        f"Setup: price={price:.2f}, MA50={candidate.technical.ma50:.2f} (uptrend={candidate.technical.is_uptrend})",
        f"RSI={candidate.technical.rsi:.1f} (bounce={candidate.technical.rsi_bounce}, momentum={candidate.technical.rsi_momentum})",
        f"Volume confirmed: {candidate.technical.volume_confirmed}",
        f"Support: {candidate.technical.support_level}, Resistance: {candidate.technical.resistance_level}",
        f"Stop: {rr.stop_price:.2f} ({rr.stop_pct:.1%}), Target: {rr.target_price:.2f} ({rr.target_pct:.1%})",
        f"Reward:Risk = {rr.reward_risk_ratio:.2f}",
    ]
    if candidate.wash_sale_flag:
        reasoning_parts.append(
            f"WASH SALE WARNING: {candidate.wash_sale_days_remaining} days remaining in window"
        )

    macro_context = (
        f"SPY {'above' if macro.spy_uptrend else 'below'} MA50 | "
        f"VIX={macro.vix_level:.1f} ({'HIGH' if macro.vix_high else 'normal'}) | "
        f"Macro gate: {macro.state.value}"
    )

    return TradeProposal(
        symbol=candidate.symbol,
        entry_price_low=entry_low,
        entry_price_high=entry_high,
        stop_price=rr.stop_price,
        target_price=rr.target_price,
        position_size_dollars=round(position_size_dollars, 2),
        reasoning="\n".join(reasoning_parts),
        expiration=expiration,
        macro_context=macro_context,
        stop_pct=rr.stop_pct,
        target_pct=rr.target_pct,
        reward_risk_ratio=rr.reward_risk_ratio,
        is_leveraged_etf=candidate.symbol in config.LEVERAGED_ETFS,
        wash_sale_flag=candidate.wash_sale_flag,
        wash_sale_days_remaining=candidate.wash_sale_days_remaining,
    )


def format_proposal_for_display(proposal: TradeProposal) -> str:
    """Human-readable summary for approval prompts."""
    lines = [
        "=" * 60,
        f"  TRADE PROPOSAL: {proposal.symbol}",
        "=" * 60,
        f"  Entry range : ${proposal.entry_price_low:.2f} – ${proposal.entry_price_high:.2f}",
        f"  Stop-loss   : ${proposal.stop_price:.2f} ({proposal.stop_pct:.1%} risk)",
        f"  Profit tgt  : ${proposal.target_price:.2f} ({proposal.target_pct:.1%} target)",
        f"  Reward:Risk : {proposal.reward_risk_ratio:.2f}",
        f"  Size        : ${proposal.position_size_dollars:.2f}",
        f"  Expires     : {proposal.expiration.strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "  Macro context:",
        f"  {proposal.macro_context}",
        "",
        "  Reasoning:",
    ]
    for line in proposal.reasoning.split("\n"):
        lines.append(f"  {line}")
    if proposal.wash_sale_flag:
        lines.append(f"\n  *** WASH SALE WARNING: {proposal.wash_sale_days_remaining} days remaining ***")
    lines.append("=" * 60)
    return "\n".join(lines)
